services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cineflow-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-YourStrong@Password123}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  api:
    build:
      context: ./CineFlowAPI
      dockerfile: Dockerfile
    container_name: cineflow-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=CineFlowDB;User Id=sa;Password=${MSSQL_SA_PASSWORD:-YourStrong@Password123};TrustServerCertificate=True
      - Tmdb__Token=${TMDB_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: CineflowFront/Dockerfile
    container_name: cineflow-nginx
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  mssql_data:
